version: '3'

services:
  my-postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2024!"
    ports:
      - "15432:5432"
    volumes:
      - D:/workspace/docker/volumes/postgresql:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
      
  my-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "horranakazekage@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2024!"
    ports:
      - "16543:80"
    depends_on:
      - my-postgres-compose
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
